name: DIPAN
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python~=3.6
  - HTSeq==0.9.1 
  - pandas==1.1.5
  - numpy==1.19.5
  - pyfasta==0.5.2
  - pip
  - pip:
    - scipy==1.5.4
